<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8AXgyUb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8AXgyUb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8AXgyUb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8AXgyUb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8AXgyUb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8AXgyUb',
    'container.build_id' => 'd8ebe7a9',
    'container.build_time' => 1560931438,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8AXgyUb');
